apiVersion: management.loft.sh/v1
kind: SharedSecret
metadata:
  name: private-nodes-aws-node-provider-credentials
  namespace: vcluster-platform
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  displayName: Private Nodes AWS Node Provider Credentials
  description: AWS credentials for the private-nodes-aws-node-provider Terraform templates
---
apiVersion: v1
kind: Secret
metadata:
  name: private-nodes-aws-node-provider-credentials
  namespace: vcluster-platform
  labels:
    terraform.vcluster.com/provider: private-nodes-aws-node-provider
    loft.sh/sharedsecret-name: private-nodes-aws-node-provider-credentials
    loft.sh/sharedsecret-namespace: vcluster-platform
type: Opaque
