apiVersion: management.loft.sh/v1
kind: NodeEnvironment
metadata:
  name: private-nodes-aws-environment
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  displayName: Private Nodes AWS Environment
  providerRef: private-nodes-aws-node-provider
  controlPlane: true
  owner:
    team: loft-admins
  properties:
    region: us-east-1
  access:
    - verbs:
        - get
      users:
        - '*'
