apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: private-nodes-aws-cluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            privateNodesAWS: 'true'
  template:
    metadata:
      name: private-nodes-aws-apps
      labels:
        use-case.demos.vcluster.com: private-nodes-aws
    spec:
      destination:
        server: '{{server}}'
        namespace: argocd
      project: default
      source:
        repoURL: 'https://github.com/loft-demos/lambda-demo-app'
        targetRevision: 'main'
        path: vcluster-use-cases/private-nodes/aws-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
        retry:
          limit: 5
          backoff:
            duration: 20s
            factor: 2
            maxDuration: 3m
